In [33]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 500

df = pd.DataFrame({
    'order_id': np.arange(1, n+1),
    'order_date': pd.date_range(start='2023-01-01', periods=n, freq='D'),
    'customer_id': np.random.randint(1000, 1100, n),
    'product_category': np.random.choice(
        ['Electronics', 'Clothing', 'Home', 'Sports', 'Books'], n
    ),
    'price': np.round(np.random.uniform(100, 1000, n), 2),
    'quantity': np.random.randint(1, 5, n),
    'discount_percent': np.random.choice([0, 5, 10, 15, 20], n)
})

# Add outliers
outlier_idx = np.random.choice(df.index, 10)
df.loc[outlier_idx, 'price'] *= 5

In [34]:
df.head()

,order_id,order_date,customer_id,product_category,price,quantity,discount_percent
0,1,2023-01-01,1051,Sports,205.03,3,20
1,2,2023-01-02,1092,Clothing,525.85,1,0
2,3,2023-01-03,1014,Home,645.49,1,5
3,4,2023-01-04,1071,Books,814.86,3,15
4,5,2023-01-05,1060,Electronics,196.03,3,5

In [35]:
df['final_amount']=(df['price']*df['quantity'])*(1-df['discount_percent']/100)

In [36]:
df.head()

,order_id,order_date,customer_id,product_category,price,quantity,discount_percent,final_amount
0,1,2023-01-01,1051,Sports,205.03,3,20,492.0720
1,2,2023-01-02,1092,Clothing,525.85,1,0,525.8500
2,3,2023-01-03,1014,Home,645.49,1,5,613.2155
3,4,2023-01-04,1071,Books,814.86,3,15,2077.8930
4,5,2023-01-05,1060,Electronics,196.03,3,5,558.6855

In [37]:
df['month']=df['order_date'].dt.to_period('M')
df

,order_id,order_date,customer_id,product_category,price,quantity,discount_percent,final_amount,month
0,1,2023-01-01,1051,Sports,205.03,3,20,492.0720,2023-01
1,2,2023-01-02,1092,Clothing,525.85,1,0,525.8500,2023-01
2,3,2023-01-03,1014,Home,645.49,1,5,613.2155,2023-01
3,4,2023-01-04,1071,Books,814.86,3,15,2077.8930,2023-01
4,5,2023-01-05,1060,Electronics,196.03,3,5,558.6855,2023-01
...,...,...,...,...,...,...,...,...,...
495,496,2024-05-10,1062,Sports,327.26,3,10,883.6020,2024-05
496,497,2024-05-11,1068,Electronics,504.65,3,0,1513.9500,2024-05
497,498,2024-05-12,1021,Books,243.04,4,20,777.7280,2024-05
498,499,2024-05-13,1092,Electronics,521.69,2,10,939.0420,2024-05
499,500,2024-05-14,1066,Electronics,949.87,1,5,902.3765,2024-05

In [44]:
df['monthly_revenue'] = df.groupby(['month', 'product_category'])['final_amount'].transform('sum')

In [45]:
df.head(30)

,order_id,order_date,customer_id,product_category,price,quantity,discount_percent,final_amount,month,monthly_revenue
0,1,2023-01-01,1051,Sports,205.03,3,20,492.0720,2023-01,11680.1920
1,2,2023-01-02,1092,Clothing,525.85,1,0,525.8500,2023-01,11972.1490
2,3,2023-01-03,1014,Home,645.49,1,5,613.2155,2023-01,2328.4475
3,4,2023-01-04,1071,Books,814.86,3,15,2077.8930,2023-01,22874.8640
4,5,2023-01-05,1060,Electronics,196.03,3,5,558.6855,2023-01,6275.1380
5,6,2023-01-06,1020,Books,865.65,3,5,2467.1025,2023-01,22874.8640
6,7,2023-01-07,1082,Sports,771.38,1,0,771.3800,2023-01,11680.1920
7,8,2023-01-08,1086,Books,467.67,1,0,467.6700,2023-01,22874.8640
8,9,2023-01-09,1074,Electronics,939.64,3,0,2818.9200,2023-01,6275.1380
9,10,2023-01-10,1074,Sports,991.84,4,0,3967.3600,2023-01,11680.1920
10,11,2023-01-11,1087,Books,284.50,4,20,910.4000,2023-01,22874.8640
11,12,2023-01-12,1099,Sports,441.31,2,0,882.6200,2023-01,11680.1920
12,13,2023-01-13,1023,Clothing,933.80,3,20,2241.1200,2023-01,11972.1490
13,14,2023-01-14,1002,Clothing,749.44,2,20,1199.1040,2023-01,11972.1490
14,15,2023-01-15,1021,Books,143.29,4,0,573.1600,2023-01,22874.8640
15,16,2023-01-16,1052,Sports,803.36,2,10,1446.0480,2023-01,11680.1920
16,17,2023-01-17,1001,Electronics,845.15,3,15,2155.1325,2023-01,6275.1380
17,18,2023-01-18,1087,Books,3877.25,3,5,11050.1625,2023-01,22874.8640
18,19,2023-01-19,1029,Clothing,819.58,3,20,1966.9920,2023-01,11972.1490
19,20,2023-01-20,1037,Clothing,842.62,1,15,716.2270,2023-01,11972.1490
20,21,2023-01-21,1001,Books,267.76,2,10,481.9680,2023-01,22874.8640
21,22,2023-01-22,1063,Sports,312.12,4,5,1186.0560,2023-01,11680.1920
22,23,2023-01-23,1059,Clothing,670.38,4,5,2547.4440,2023-01,11972.1490
23,24,2023-01-24,1020,Sports,917.08,4,20,2934.6560,2023-01,11680.1920
24,25,2023-01-25,1032,Clothing,384.58,1,0,384.5800,2023-01,11972.1490
25,26,2023-01-26,1075,Clothing,629.48,1,10,566.5320,2023-01,11972.1490
26,27,2023-01-27,1057,Home,714.68,3,20,1715.2320,2023-01,2328.4475
27,28,2023-01-28,1021,Clothing,506.75,4,10,1824.3000,2023-01,11972.1490
28,29,2023-01-29,1088,Electronics,742.40,1,0,742.4000,2023-01,6275.1380
29,30,2023-01-30,1048,Books,909.70,3,0,2729.1000,2023-01,22874.8640

[ 1  8 27 64]